require("class")
require("deck")
require("game")
require("helper")
require("macro")
require("opt")
require("player")
require("query")
require("resmng")

deck = Deck:new()
game = Game:new()

deck:init()
local hero_class = require("hero.zhou_yu")
local player = hero_class.new(1, 218, 1)
helper.insert(player.hand_cards, deck:draw(4))
print(#player.hand_cards)
player:draw()
print(#player.hand_cards)